In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

In [82]:
df = pd.read_csv('processed_energy_data.csv')

C:\Users\ssttg\AppData\Local\Temp\ipykernel_15520\3426351519.py:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('processed_energy_data.csv')

In [83]:
df.head()

,time,use [kW],gen [kW],House overall [kW],Dishwasher [kW],Furnace 1 [kW],Furnace 2 [kW],Home office [kW],Fridge [kW],Wine cellar [kW],...,precipIntensity,dewPoint,precipProbability,total_energy_use,net_energy,hour,day,month,daily_cost,is_off_peak
0,2016-01-01 05:00:00,0.932833,0.003483,0.932833,0.000033,0.020700,0.061917,0.442633,0.124150,0.006983,...,0.0,24.4,0.0,2.580650,-2.577167,5,1,1,25.806500,1
1,2016-01-01 05:00:01,0.934333,0.003467,0.934333,0.000000,0.020717,0.063817,0.444067,0.124000,0.006983,...,0.0,24.4,0.0,2.587100,-2.583633,5,1,1,25.871000,1
2,2016-01-01 05:00:02,0.931817,0.003467,0.931817,0.000017,0.020700,0.062317,0.446067,0.123533,0.006983,...,0.0,24.4,0.0,2.582117,-2.578650,5,1,1,25.821167,1
3,2016-01-01 05:00:03,1.022050,0.003483,1.022050,0.000017,0.106900,0.068517,0.446583,0.123133,0.006983,...,0.0,24.4,0.0,2.855050,-2.851567,5,1,1,28.550500,1
4,2016-01-01 05:00:04,1.139400,0.003467,1.139400,0.000133,0.236933,0.063983,0.446533,0.122850,0.006850,...,0.0,24.4,0.0,3.214750,-3.211283,5,1,1,32.147500,1

In [84]:
def get_real_time_tariff(hour):
    if 0 <= hour < 6:
        return 1.0  # Off-peak rate
    elif 6 <= hour < 12:
        return 2.5  # Mid-rate
    elif 12 <= hour < 18:
        return 3.5  # Peak rate
    else:
        return 4.0  # High-demand rate

In [85]:
# Apply the real-time tariff function
df['tariff_rate'] = df['hour'].apply(get_real_time_tariff)

In [86]:
df['tariff_rate']

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ...
503905    1.0
503906    1.0
503907    1.0
503908    1.0
503909    1.0
Name: tariff_rate, Length: 503910, dtype: float64

In [87]:
#df.to_csv('processed_energy_data_1.csv', index=False)

In [94]:
# Function to simulate real-time monitoring of data
def simulate_real_time_data(df, start_index=0, interval=60):
    current_time_index = start_index
    while current_time_index < len(df):
        # Select the row corresponding to the current index
        current_row = df.iloc[current_time_index]

        # Display the real-time tariff rate
        current_time = current_row['time']
        current_usage = current_row['use [kW]']
        current_generation = current_row['gen [kW]']
        current_tariff_rate = current_row['tariff_rate']

        print(f"Time: {current_time}, Usage: {current_usage} kW, Generation: {current_generation} kW, Tariff Rate: Rs {current_tariff_rate} / kWh")

        # Sleep to simulate real-time monitoring (adjust the interval for faster or slower simulation)
        time.sleep(1)

        current_time_index += interval  # Update the index by 'interval' rows for each iteration

In [95]:
# Step 5: Plot a visualization of tariff rates over time
def plot_tariff_rates(df):
    plt.figure(figsize=(12, 6))
    plt.plot(df['time'], df['tariff_rate'], label='Tariff Rate (Rs/kWh)', color='purple')
    plt.title('Real-Time Tariff Monitoring')
    plt.xlabel('Time')
    plt.ylabel('Tariff Rate (Rs/kWh)')
    plt.grid(True)
    plt.legend()
    plt.show()

In [96]:
# Simulate real-time tariff monitoring
print("Starting Real-Time Tariff Simulation...")
simulate_real_time_data(df.head(1000), start_index=0, interval=60)

Starting Real-Time Tariff Simulation...
Time: 2016-01-01 05:00:00, Usage: 0.932833333 kW, Generation: 0.003483333 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:01:00, Usage: 0.465133333 kW, Generation: 0.00345 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:02:00, Usage: 0.539166667 kW, Generation: 0.003516667 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:03:00, Usage: 0.380316667 kW, Generation: 0.003433333 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:04:00, Usage: 0.940616667 kW, Generation: 0.0035 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:05:00, Usage: 0.494116667 kW, Generation: 0.00345 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:06:00, Usage: 0.36665 kW, Generation: 0.003433333 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:07:00, Usage: 0.501916667 kW, Generation: 0.003416667 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:08:00, Usage: 0.2978 kW, Generation: 0.0034 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:09:00, Usage: 0.3655 kW, Generation: 0.07335 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:10:00, Usage: 0.647683333 kW, Generation: 0.09365 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:11:00, Usage: 1.81835 kW, Generation: 0.020216667 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:12:00, Usage: 1.473566667 kW, Generation: 0.012366667 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:13:00, Usage: 3.805483333 kW, Generation: 0.031016667 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:14:00, Usage: 1.48975 kW, Generation: 0.012816667 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:15:00, Usage: 1.317716667 kW, Generation: 0.011033333 kW, Tariff Rate: Rs 1.0 / kWh
Time: 2016-01-01 05:16:00, Usage: 1.130516667 kW, Generation: 0.002066667 kW, Tariff Rate: Rs 1.0 / kWh